name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to GitHub Pagesages
        uses: peaceiris/actions-gh-pages@v3ions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}GITHUB_TOKEN }}
          publish_dir: .out
          force_orphan: truece_orphan: true
